# Generated by Django 5.2.1 on 2025-06-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_postdislike_created_at_postdislike_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdislike',
            name='comment',
        ),
    ]
