# Generated by Django 5.2.1 on 2025-06-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_postdislike_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dislike', to='myapp.post'),
        ),
    ]
