# Generated by Django 5.2.1 on 2025-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_profile_followers_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_profiles', to='myapp.profile'),
        ),
    ]
